afk:
  scope-start: 30      # 玩家无动作 n 秒后视为挂机
  scope-end: 43200     # 超过 n 秒后,则不再发放奖励

  # 挂机奖励黑名单: 写上名字的玩家,即便挂机也不会获得奖励
  blacklist:
    - 'player1'
    - 'player2'
  # 挂机奖励
  gift:
    cycle: 5   # 挂机的玩家 n 秒给与一次奖励
    vault: 5   # 奖励 n 点云币
    exp: 10    # 奖励 n 点经验值
  # 发送给玩家的信息, 如果没有内容则不发送
  message:
    # [未实现]玩家进入挂机状态时发送消息
    afk: '你去哪了?'
    # [未实现]玩家回来时候显示消息
    active: '回来啦!'
    # 每次发送挂机奖励时候发送消息
    gift: '给你一点挂机礼物'