afk:
  scope-start: 5        # 玩家无动作 n 秒后视为挂机
  scope-end: 43200      # 超过 n 秒后,则不再发放奖励
  particle: 10          # 玩家挂机以后周围出现粒子数量(1~50),填0则不显示

  # 挂机奖励
  gift:
    cycle: 3   # 挂机的玩家 n 秒给与一次奖励
    vault: 5   # 奖励 n 点云币
    exp: 10    # 奖励 n 点经验值


  # 发送给玩家的信息, 不填则不发送, 颜色符号为'&'
  message:
    # 玩家进入挂机状态时发送消息
    afk: '&6你去哪了?'
    # 玩家回来时候显示消息
    active: '&6你回来啦!'
    # 每次发送挂机奖励时候发送消息
    gift: '&7给你一点挂机礼物'

  # 玩家进入挂机状态时候的屏幕显示
  title:
    main: '&6你去哪儿了'
    sub: '&f不要吃太多饼干'

  # 挂机奖励黑名单: 写上名字的玩家,即便挂机也不会获得奖励
  blacklist:
    - 'player1'
    - 'player2'



